# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: https://api.github.com/repos/${{github.repository}}/issues
      URL_ROOT: https://github.com/repos/${{github.repository}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 拉当前分支最新代码
        uses: actions/checkout@v2
      - name: 创建issue
        run: |
          branch_name=`git rev-parse --abbrev-ref HEAD`
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "authorization: Bearer ${{secrets.TEAM_TOKENT}}" \
          ${{env.ISSUE_URL}} \
          -d '{"title":"test use: ${{github.event.head_commit.message}}", \
          "body": "[查看详情](${{env.URL_ROOT}}/actions/runs/${{github.run_id}})", \
          "assignees": ["${{github.event.head_commit.author.username}}"]}'
